/* quick-simcom.js — SIMCom quick-command catalog: the AT commands each sidebar group offers
   (the "AT Commands" combo inside every wizard, and the per-group list).
   Keyed by wizard id, in the same shape as any other quick table: [label, command, edit?] —
   a 1 in the third field means the command has __PARAMS__ to fill in before sending.
   Attached to the SIMCom profiles (profiles-simcom.js); the divergent families override just
   the groups that change (QUICK_SIM70X0 / QUICK_SIM7022).
   (part of the AT console · classic script, shared global scope — concatenated in order) */

/** @type {QuickTable} */
const QUICK_SIMCOM = {
  basics: [
    ['i0_0', "AT"],
    ['i0_1', "ATI"],
    ['i0_2', "AT+SIMCOMATI"],
    ['i0_3', "AT+CGMR"],
    ['i0_4', "AT+CGSN"],
    ['i0_5', "ATE0"],
    ['i0_6', "AT+CMEE=2"],
    ['i0_7', "AT+CRESET"],
    ['i0_8', "AT+CPAS"],
    ['i2_1', "AT+CSQ"],
    ['i2_2', "AT+CESQ"],
    ['i2_3', "AT+CPSI?"],
    ['i2_4', "AT+COPS?"],
    ['i2_5', "AT+CEREG?"],
    ['i2_6', "AT+CGATT?"],
    ['i2_7', "AT+CGDCONT?"],
    ['i3_3', "AT+CGDCONT=1,\"IP\",\"__APN__\"", 1],
    ['i2_8', "AT+CREG?"],
    ['i2_9', "AT+CGREG?"],
    ['i2_10', "AT+CNMP=__MODE__", 1],
    ['i2_11', "AT+CNBP?"],
    ['i2_12', "AT+CNSMOD?"],
    ['i2_13', "AT+CGAUTH=1,1,\"__USER__\",\"__PASS__\"", 1],
  ],
  sim: [
    ['i1_6', "AT+CPIN?"],
    ['i1_0', "AT+CICCID"],
    ['i1_1', "AT+CIMI"],
    ['i1_2', "AT+CSPN?"],
    ['i1_3', "AT+CLCK=\"SC\",2"],
    ['i1_4', "AT+CPWD=\"SC\",\"__OLD__\",\"__NEW__\"", 1],
    ['i1_5', "AT+SPIC"],
  ],
  ping: [
    ['i4_9', "AT+CPING=\"8.8.8.8\",1,4"],
    ['i4_10', "AT+CPING=\"__HOST__\",1,4", 1],
  ],
  tcpudp: [
    ['i4_0', "AT+NETOPEN"],
    ['i3_1', "AT+IPADDR"],
    ['i4_1', "AT+CIPRXGET=1"],
    ['i4_2', "AT+CIPOPEN=0,\"TCP\",\"__HOST__\",__PORT__", 1],
    ['i4_3', "AT+CIPOPEN=1,\"UDP\",\"__HOST__\",__PORT__", 1],
    ['i4_4', "AT+CIPSEND=__LINK__,__LEN__", 1],
    ['i4_5', "AT+CIPRXGET=2,__LINK__,1460", 1],
    ['i4_6', "AT+CIPOPEN?"],
    ['i4_7', "AT+CIPCLOSE=__LINK__", 1],
    ['i4_8', "AT+NETCLOSE"],
    ['i4_11', "AT+CIPACK=__LINK__", 1],
    ['i4_12', "AT+CIPSRIP=1"],
    ['i4_13', "AT+CIPHEAD=1"],
    ['i4_14', "AT+CIPMODE=0"],
    ['i4_15', "AT+SERVERSTART=__PORT__,0", 1],
    ['i4_16', "AT+SERVERSTOP=0"],
  ],
  http: [
    ['i5_0', "AT+HTTPINIT"],
    ['i5_1', "AT+HTTPPARA=\"URL\",\"__URL__\"", 1],
    ['i5_2', "AT+HTTPACTION=0"],
    ['i5_3', "AT+HTTPACTION=1"],
    ['i5_4', "AT+HTTPHEAD"],
    ['i5_5', "AT+HTTPREAD=0,1024"],
    ['i5_6', "AT+HTTPTERM"],
    ['i5_7', "AT+HTTPREADFILE=\"__PATH__\"", 1],
    ['i5_8', "AT+HTTPPOSTFILE=\"__PATH__\",1", 1],
  ],
  ftp: [
    ['i6_0', "AT+CFTPSSTART"],
    ['i6_1', "AT+CFTPSLOGIN=\"__HOST__\",21,\"__USER__\",\"__PASS__\",0", 1],
    ['i6_2', "AT+CFTPSLIST=\"/\""],
    ['i6_3', "AT+CFTPSGETFILE=\"__PATH__\",0", 1],
    ['i6_4', "AT+CFTPSPUTFILE=\"__PATH__\",0", 1],
    ['i6_5', "AT+CFTPSLOGOUT"],
    ['i6_6', "AT+CFTPSSTOP"],
    ['i6_7', "AT+CFTPSPWD"],
    ['i6_8', "AT+CFTPSCWD=\"__PATH__\"", 1],
    ['i6_9', "AT+CFTPSMKD=\"__DIR__\"", 1],
    ['i6_10', "AT+CFTPSDELE=\"__FILE__\"", 1],
    ['i6_11', "AT+CFTPSSIZE=\"__FILE__\"", 1],
    ['i6_12', "AT+CFTPSTYPE=I"],
    ['i6_13', "AT+CFTPSSLCFG=__CTX__", 1],
  ],
  mqtt: [
    ['i7_0', "AT+CMQTTSTART"],
    ['i7_1', "AT+CMQTTACCQ=0,\"__CLIENTID__\",0", 1],
    ['i7_2', "AT+CMQTTCONNECT=0,\"tcp://__HOST__:1883\",60,1", 1],
    ['i7_3', "AT+CMQTTSUBTOPIC=0,__LEN__,1", 1],
    ['i7_4', "AT+CMQTTSUB=0"],
    ['i7_5', "AT+CMQTTTOPIC=0,__LEN__", 1],
    ['i7_6', "AT+CMQTTPAYLOAD=0,__LEN__", 1],
    ['i7_7', "AT+CMQTTPUB=0,1,60"],
    ['i7_8', "AT+CMQTTDISC=0,60"],
    ['i7_9', "AT+CMQTTSTOP"],
    ['i7_10', "AT+CMQTTUNSUBTOPIC=0,__LEN__", 1],
    ['i7_11', "AT+CMQTTUNSUB=0,0"],
    ['i7_12', "AT+CMQTTWILLTOPIC=0,__LEN__", 1],
    ['i7_13', "AT+CMQTTWILLMSG=0,__LEN__,1", 1],
  ],
  lwm2m: [
    ['Start service', "AT+LWSTART"],
    ['Config server', "AT+LWCNF=0,\"server\",\"__HOST__\"", 1],
    ['Config port', "AT+LWCNF=0,\"serverport\",\"__PORT__\"", 1],
    ['Config endpoint', "AT+LWCNF=0,\"endpointname\",\"__NAME__\"", 1],
    ['Config lifetime', "AT+LWCNF=0,\"lifetime\",\"__SECS__\"", 1],
    ['Register', "AT+LWOPEN=0"],
    ['Add object', "AT+LWADDOBJ=0,__OBJ__,0,__CNT__,__RES1__", 1],
    ['Set resource', "AT+LWSET=0,,\"__URI__\",\"S\",__LEN__,\"__VALUE__\"", 1],
    ['Get resource', "AT+LWGET=0,\"__URI__\"", 1],
    ['Notify', "AT+LWSEND=0,6"],
    ['Send', "AT+LWSEND=0,7"],
    ['Deregister', "AT+LWCLOSE=0"],
    ['Stop service', "AT+LWSTOP"],
  ],
  coap: [
    ['Start (PDP)', "AT+COAPSTART"],
    ['Open session', "AT+COAPOPEN=\"__HOST__\",__PORT__", 1],
    ['Config head', "AT+COAPHEAD=0,__MSGID__,1,\"1\"", 1],
    ['Config option', "AT+COAPOPTION=0,1,__OPTNUM__,\"__VALUE__\"", 1],
    ['Send message', "AT+COAPSEND=0,\"con\",\"get\",__LEN__,\"__DATA__\"", 1],
    ['Send transparent', "AT+COAPSENDTX=0,\"con\",\"post\",__LEN__", 1],
    ['Close session', "AT+COAPCLOSE=0"],
    ['Stop (PDP)', "AT+COAPSTOP"],
  ],
  fs: [
    ['i8_0', "AT+FSCD?"],
    ['i8_1', "AT+FSCD=__DIR__", 1],
    ['i8_2', "AT+FSLS"],
    ['i8_3', "AT+FSMEM"],
    ['i8_4', "AT+FSMKDIR=__NAME__", 1],
    ['i8_5', "AT+FSDEL=__NAME__", 1],
    ['i8_6', "AT+FSATTRI=__NAME__", 1],
    ['i8_7', "AT+CFTRANRX=\"__PATH__\",__LEN__", 1],
    ['i8_8', "AT+CFTRANTX=\"__PATH__\"", 1],
    ['i8_9', "AT+FSRMDIR=\"__DIR__\"", 1],
    ['i8_10', "AT+FSRENAME=\"__OLD__\",\"__NEW__\"", 1],
    ['i8_11', "AT+FSCOPY=\"__SRC__\",\"__DST__\"", 1],
    ['i8_12', "AT+FSOPEN=\"__FILE__\",0", 1],
    ['i8_13', "AT+FSREAD=__HANDLE__,__LEN__", 1],
    ['i8_14', "AT+FSWRITE=__HANDLE__,__LEN__", 1],
    ['i8_15', "AT+FSCLOSE=__HANDLE__", 1],
  ],
  gnss: [
    ['i9_0', "AT+CGNSSPWR=1"],
    ['i9_1', "AT+CGNSSINFO"],
    ['i9_2', "AT+CGNSSPWR=0"],
    ['i9_3', "AT+CGNSSMODE=__MODE__", 1],
    ['i9_4', "AT+CGPSCOLD"],
    ['i9_5', "AT+CGPSWARM"],
    ['i9_6', "AT+CGPSHOT"],
    ['i9_7', "AT+CGNSSNMEA=__MASK__", 1],
    ['i9_8', "AT+CGNSSPORTSWITCH=1,1"],
    ['i9_9', "AT+CAGPS"],
  ],
  lbs: [
    ['i10_0', "AT+CLBS=1,1"],
    ['i10_1', "AT+CLBSCFG=0,1"],
  ],
  sms: [
    ['i11_0', "AT+CMGF=1"],
    ['i11_1', "AT+CMGL=\"ALL\""],
    ['i11_2', "AT+CMGS=\"__NUMERO__\"", 1],
    ['i11_3', "AT+CPMS=\"SM\",\"SM\",\"SM\""],
    ['i11_4', "AT+CNMI=2,1,0,0,0"],
    ['i11_5', "AT+CMGR=__INDEX__", 1],
    ['i11_6', "AT+CMGD=__INDEX__", 1],
    ['i11_7', "AT+CMGW=\"__NUMBER__\"", 1],
    ['i11_8', "AT+CMSS=__INDEX__", 1],
    ['i11_9', "AT+CSCA?"],
    ['i11_10', "AT+CSMP=17,167,0,0"],
  ],
  tls: [
    ['i12_0', "AT+CCERTLIST"],
    ['i12_1', "AT+CSSLCFG?"],
    ['i12_2', "AT+CCERTDOWN=\"__NAME__\",__LEN__", 1],
    ['i12_3', "AT+CCERTDELE=\"__NAME__\"", 1],
    ['i12_4', "AT+CCHSSLCFG=__SESSION__,__CTX__", 1],
    ['i12_5', "AT+CCHSET=1,1"],
    ['i12_6', "AT+CCHADDR=__SESSION__", 1],
  ],
  time: [
    ['i13_0', "AT+CCLK?"],
    ['i13_1', "AT+CNTP"],
    ['i13_2', "AT+CDNSGIP=\"__HOST__\"", 1],
    ['i13_3', "AT+CTZU=1"],
    ['i13_4', "AT+CTZR=1"],
  ],
  hw: [
    ['i15_0', "AT+CBC"],
    ['i15_1', "AT+CPMUTEMP"],
    ['i15_2', "AT+CFUN=1,1"],
    ['i15_3', "AT+CADC?"],
    ['i15_4', "AT+CGDRT=__PIN__,__DIR__", 1],
    ['i15_5', "AT+CGSETV=__PIN__,__VAL__", 1],
    ['i15_6', "AT+CGGETV=__PIN__", 1],
    ['i15_7', "AT+CVALARM=1,3450,4200"],
    ['i14_0', "AT+IPR=__BAUD__", 1],
    ['i14_1', "AT+ICF=3,3"],
    ['i14_2', "AT+IFC=2,2"],
    ['i14_3', "AT+CSCLK=__MODE__", 1],
    ['i14_4', "AT+CMUX=0"],
  ],
  wifi: [
    ['i16_0', "AT+CWSTASCAN"],
    ['i16_1', "AT+CWSTASCAN=1"],
    ['i16_2', "AT+CWSTASCAN?"],
    ['i16_3', "AT+CWSTASCANEX=1,1,10,30,0"],
    ['i16_4', "AT+CWSTASCANEX"],
    ['i16_5', "AT+CWSTASCAN=?"],
  ],
  jam: [
    ['i17_0', "AT+SJDR=1"],
    ['i17_1', "AT+SJDR=0"],
    ['i17_2', "AT+SJDR?"],
    ['i17_3', "AT+SJDCFG?"],
    ['i17_4', "AT+SJDCFG=\"period\",5"],
    ['i17_5', "AT+SJDCFG=\"detecstat\",1"],
  ],
  mail: [
    ['i18_0', "AT+CSMTPSSRV?"],
    ['i18_1', "AT+CSMTPSAUTH?"],
    ['i18_2', "AT+CSMTPSRCPT?"],
    ['i18_3', "AT+CSMTPSSEND"],
    ['i18_4', "AT+CSMTPSSTOP"],
    ['i18_5', "AT+CSMTPSCLEAN"],
  ],
  pb: [
    ['i19_0', "AT+CPBS?"],
    ['i19_1', "AT+CPBR=1,250"],
    ['i19_2', "AT+CPBF=\"__TEXT__\"", 1],
    ['i19_3', "AT+CPBW=,\"__NUM__\",145,\"__NAME__\"", 1],
    ['i19_4', "AT+CNUM"],
    ['i19_5', "AT+CPBS=?"],
  ],
  voice: [
    ['i20_0', "ATD__NUM__;", 1],
    ['i20_1', "ATA"],
    ['i20_2', "AT+CHUP"],
    ['i20_3', "AT+CLCC"],
    ['i20_4', "AT+CLIP=1"],
    ['i20_5', "AT+VTS=__D__", 1],
  ],
  ble: [
    ['i21_0', "AT+BLEPOWER=1"],
    ['i21_1', "AT+BLEPOWER=0"],
    ['i21_2', "AT+BLESTATUS?"],
    ['i21_3', "AT+BLEADDR?"],
    ['i21_4', "AT+BLECREG"],
    ['i21_5', "AT+BLESCAN=0,1"],
    ['i21_6', "AT+BLESCAN=0,0"],
    ['i21_7', "AT+BLESREG"],
    ['i21_8', "AT+BLESLSTART=0"],
    ['i21_9', "AT+BLECCON=__IDX__", 1],
  ],
};
